Areas/GM/Pages/PO/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Models;
using Nkgjjm.StoredProcedure;

namespace Nkgjjm.Areas.GM.Pages.PO
{
    public class IndexModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public IndexModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<SPPoList> PoMaster { get; set; } = default!;
        public int TotalPo { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {
                if (_context.TblPoChild != null)
                {
                    PoMaster = await _context.SPPoList.FromSqlRaw("SPPoList").ToListAsync();
                    TotalPo = await _context.TblPoMaster.CountAsync();
                }
                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }
        public IList<SPPoSearch> SpPoSearch { get; set; }
        public async Task<IActionResult> OnGetSearch(string PoNo)
        {
            var Po = new SqlParameter("@PoNo", PoNo);
            SpPoSearch = await _context.SPPoSearch.FromSqlRaw("SPPoSearch @PoNo", Po).ToListAsync();

            return Page();
        }
    }
}

Areas/GM/Pages/PO/PoDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Models;
using Nkgjjm.StoredProcedure;

namespace Nkgjjm.Areas.GM.Pages.PO
{
    public class PoDetailModel : PageModel
    {
        ApplicationDbContext _context;
        public PoDetailModel(ApplicationDbContext context)
        {
            _context = context; 

        }
        public List<SPPoMasterDetail> SPPoMasterDetail { get; set; }
        public List<SPPoDetail> SPPoDetail { get; set; }
        public async Task<IActionResult> OnGet(string PoNo)
        {

            var Po = new SqlParameter("@Pono", PoNo);
            SPPoMasterDetail = await _context.SPPoMasterDetail.FromSqlRaw("SPPoMasterDetail @Pono", Po).ToListAsync();
            SPPoDetail = await _context.SPPoDetail.FromSqlRaw("SPPoDetail @Pono", Po).ToListAsync();

            return Page();
        }
    }
}

Areas/GM/Pages/PO/UploadGrn.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Classes;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.GM.Pages.PO
{
    public class UploadGrnModel : PageModel
    {
        ApplicationDbContext Context;
        IWebHostEnvironment Environmet;
        [BindProperty]
        public IFormFile Uploadgrn { get; set; }
        public string UploadgrnName { get; set; }
        
        public UploadGrnModel(ApplicationDbContext context, IWebHostEnvironment Env)
        {
            Context = context;
            Environmet = Env;
        }
        [BindProperty]
        public string po { get; set; }
        public IActionResult OnGet(string PoNo)
        {
            po = PoNo;
            return Page();
        }
        public IActionResult OnPost(string PoNo)
        {
            //Upload u = new Upload(Environmet);            
            //UploadgrnName = u.UploadImage(Uploadgrn, "Grn");
            //var grn = await Context.TblPoMaster.SingleOrDefaultAsync(e => e.Pono == PoNo);
            //if(grn != null)
            //{
            //    grn.Grn = UploadgrnName;
            //}
            //await Context.SaveChangesAsync();
            return Page();
        }
    }
}

Areas/GM/Pages/VillageIncharge/UploadGrn.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nkgjjm.Areas.GM.Pages.VillageIncharge
{
    public class UploadGrnModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Areas/GM/Pages/Warehouseincharge/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Nkgjjm.Classes;
using Nkgjjm.Models;
using Nkgjjm.StoredProcedure;

namespace Nkgjjm.Areas.GM.Pages.Warehouseincharge
{
    public class DetailsModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;
        IWebHostEnvironment Environmet;

        public string InwardDocument { get; set; }

        [BindProperty]
        public PoVehicleDetail PoVehicleDetail { get; set; }

        public DetailsModel(ApplicationDbContext context, IWebHostEnvironment Env)
        {
            _context = context;
            Environmet = Env;
        }

        public List<SPMaterialReceivedCorrespondenceToPo> SPMaterialReceivedCorrespondenceToPo { get; set; } = default!;
        public string Ponumber { get; set; }
        public int Warehouseid { get; set; }
        public async Task<IActionResult> OnGetAsync(string Pono)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {

                var po = new SqlParameter("@PoId", Pono);
                var challan = new SqlParameter("@Challannumber", DBNull.Value);
                var Whid = new SqlParameter("@Warehouseid", Warehouseid);
                SPMaterialReceivedCorrespondenceToPo = await _context.SPMaterialReceivedCorrespondenceToPo.FromSqlRaw("SPMaterialReceivedCorrespondenceToPo @PoId,@Challannumber,@Warehouseid", po, challan, Whid).ToListAsync();
                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }
        [BindProperty]
        public IFormFile UploadDoc { get; set; }
        public async Task<IActionResult> OnPostReceiveditem(string Ponumber, int warehousename)
        {
            try
            {
                Upload u = new Upload(Environmet);
                InwardDocument = u.UploadImage(UploadDoc, "InwardDocument");
                PoVehicleDetail.PoNo = Ponumber;
                PoVehicleDetail.SupportedDocument = InwardDocument;
                await _context.TblPoVehicleDetail.AddAsync(PoVehicleDetail);


                string Receiveditem = Request.Form["jobworkdesc"];
                DataTable dt = JsonConvert.DeserializeObject<DataTable>(Receiveditem);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    if (!string.IsNullOrEmpty(dt.Rows[i][1].ToString()))
                    {
                        Int64 Productid = Convert.ToInt64(dt.Rows[i][0].ToString());
                        string Qty = Convert.ToString(dt.Rows[i][1]);
                        double Challanqty = Convert.ToDouble(dt.Rows[i][2]);
                        MaterialReceivedbyPo received = new MaterialReceivedbyPo()
                        {
                            ItemId = Productid,
                            RcvdQty = Convert.ToDouble(Qty),
                            PoNo = Ponumber,
                            Challanqty = Challanqty,
                            Challan_Invoicenumber = PoVehicleDetail.ChallanNumber,
                            Warehouse = warehousename
                        };
                        await _context.TblMaterialReceivedbyPo.AddAsync(received);
                        await _context.SaveChangesAsync();
                    }
                }
            }
            catch (Exception ex)
            {

            }
            return RedirectToPage("Index");
        }
    }
}

Areas/HeadOffice/Pages/Blocks/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.Panel.Pages.Blocks
{
    public class CreateModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public CreateModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> OnGet()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {
                District = await _context.TblDistrict.Select(a => new SelectListItem { Text = a.District, Value = a.id.ToString() }).ToListAsync();

                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }

        [BindProperty]
        public DistBlock DistBlock { get; set; } = default!;

        [BindProperty]
        public List<SelectListItem> District { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {

                await _context.TblBlock.AddAsync(DistBlock);
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {

            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/HeadOffice/Pages/Blocks/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.Panel.Pages.Blocks
{
    public class EditModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public EditModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DistBlock DistBlock { get; set; } = default!;
        [BindProperty]
        public List<SelectListItem> District { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {
                try
                {
                    if (id == null || _context.TblBlock == null)
                    {
                        return NotFound();
                    }
                    District = await _context.TblDistrict.Select(d => new SelectListItem { Text = d.District, Value = d.id.ToString() }).ToListAsync();
                    var distblock = await _context.TblBlock.FirstOrDefaultAsync(m => m.Id == id);
                    if (distblock == null)
                    {
                        return NotFound();
                    }
                    DistBlock = distblock;
                }
                catch (Exception)
                {

                }
            }
            else
            {
                Redirect("~/Index");
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(DistBlock).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DistBlockExists(DistBlock.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DistBlockExists(int id)
        {
          return (_context.TblBlock?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Areas/HeadOffice/Pages/Contractor/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nkgjjm.Classes;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.Panel.Pages.Contractor
{
    public class CreateModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public CreateModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {
                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }

        [BindProperty]
        public Contractors Contractors { get; set; } = default!;

        GetUserDate date = new GetUserDate();
        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                if (!ModelState.IsValid || _context.TblContractor == null || Contractors == null)
                {
                    return Page();
                }
                Contractors.AddedDate = date.ReturnDate();
                _context.TblContractor.Add(Contractors);
                await _context.SaveChangesAsync();
            }
            catch(Exception)
            {

            }
            return RedirectToPage("./Index");
        }
    }
}

Areas/HeadOffice/Pages/Contractor/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.Panel.Pages.Contractor
{
    public class EditModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public EditModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Contractors Contractors { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {

                if (id == null || _context.TblContractor == null)
                {
                    return NotFound();
                }

                var contractors = await _context.TblContractor.FirstOrDefaultAsync(m => m.ContractorId == id);
                if (contractors == null)
                {
                    return NotFound();
                }
                Contractors = contractors;
                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Contractors).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ContractorsExists(Contractors.ContractorId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ContractorsExists(int id)
        {
            return (_context.TblContractor?.Any(e => e.ContractorId == id)).GetValueOrDefault();
        }
    }
}

Areas/HeadOffice/Pages/JobWorkCategory/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nkgjjm.Models;

namespace Nkgjjm.Areas.Panel.Pages.JobWorkCategory
{
    public class CreateModel : PageModel
    {
        private readonly Nkgjjm.Models.ApplicationDbContext _context;

        public CreateModel(Nkgjjm.Models.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Login")))
            {
                return Page();
            }
            else
            {
                return Redirect("~/Index");
            }
        }

        [BindProperty]
        public JobWorkcategories JobWorkcategories { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _context.TblJobWorkCategory == null || JobWorkcategories == null)
            {
                return Page();
            }

            _context.TblJobWorkCategory.Add(JobWorkcategories);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Areas/HeadOffice/Pages/PO/Delete.cshtml
@page
@model Nkgjjm.Areas.Panel.Pages.PO.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pochild</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pochild.Pono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pochild.Pono)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pochild.Itemid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pochild.Itemid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pochild.Qty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pochild.Qty)
        </dd>
        
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Pochild.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Areas/HeadOffice/Pages/PO/Details.cshtml
@page
@model Nkgjjm.Areas.Panel.Pages.PO.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div class="top-bar">
    <nav aria-label="breadcrumb" class="-intro-x mr-auto hidden sm:flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Application</a></li>
            <li class="breadcrumb-item active" aria-current="page">Goods Receiving Note</li>
        </ol>
    </nav>
    <!-- END: Account Menu -->
</div>
<h2 class="intro-y text-lg font-medium mt-0" style="background-color:#02B9B5; text-align:center; font-weight:bolder; color:white;">
    Goods Receiving Note
</h2>
<form method="post"  asp-page-handler="Receiveditem" enctype="multipart/form-data">
    <div id="horizontal-form" class="p-5">
        <div class="preview">
            <div class="form-inline">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Po Id </strong></label>
                <input type="text" name="Ponumber" class="form-control" value="@Model.Ponumber" readonly id="searchtext" />

            </div>
            <div class="form-inline mt-5">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Challan/ Invoice number</strong></label>
                <input type="text" name="Invoicenumber" asp-for="pomaster.ChallanNumber" class="form-control" id="searchtext" style="background-color:wheat;" />

            </div>
            <div class="form-inline mt-5">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Challan/ Invoice Date</strong></label>
                <input type="date" name="Invoicedate" asp-for="pomaster.Challan_InvoiceDate" class="form-control" id="searchtext" style="background-color:wheat;" />

            </div>
             <div class="form-inline mt-5">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Vehicle Number</strong></label>
                <input type="text" name="Vehiclenumber" asp-for="pomaster.VehicleNumber" class="form-control" id="searchtext" style="background-color:wheat;" />

            </div>
            <div class="form-inline mt-5">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>LR/Bilty No</strong></label>
                <input type="text" name="Biltynumber" asp-for="pomaster.LR_BiltyNo" class="form-control" id="searchtext" style="background-color:wheat;" />

            </div>
            <div class="form-inline mt-5">

                <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Transporter Name</strong></label>
                <input type="text" name="Transportername" asp-for="pomaster.TransporterName" class="form-control" id="searchtext" style="background-color:wheat;" />

            </div>
        </div>
    </div>
    @if (Model.SPMaterialReceivedCorrespondenceToPo != null && Model.SPMaterialReceivedCorrespondenceToPo.Count > 0)
    {

        <div class="grid grid-cols-12 gap-6 mt-0">
            <!-- BEGIN: Data List -->
            <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                <table class="table table-report" id="orders">

                    <tr>
                        <th class="text-center whitespace-nowrap">
                            Item Code
                        </th>
                        <th class="text-center whitespace-nowrap">
                            Item Name
                        </th>
                        <th class="text-center whitespace-nowrap">
                           Ordered Qty
                        </th>
                        <th class="text-center whitespace-nowrap">
                            Earlier Received Qty
                        </th>

                        <th class="text-center whitespace-nowrap">
                            Todays Rcvd Qty
                        </th>
                          <th class="text-center whitespace-nowrap">
                            Invoice/ CHallan Qty
                        </th>
                         <th class="text-center whitespace-nowrap">
                            Physical/Rcvd Qty
                        </th>
                        <th class="text-center whitespace-nowrap">
                            Short/Excess
                        </th>
                        <th class="text-center whitespace-nowrap">
                            Balance Qty
                        </th>

                    </tr>
                    @foreach (var item in Model.SPMaterialReceivedCorrespondenceToPo)
                    {
                        @*double TotalQty = item.Qty;
                double Pickedqty = item.Pickedqty;
                double BalanceQty = TotalQty - Pickedqty;*@
                        <tr>
                            <td class="text-center">@item.ItemCode</td>
                            <td class="text-center">@item.ItemName</td>
                            <td class="text-center"><input type="text" class="form-control Receivedqty" readonly value="@item.Qty" /></td>
                            <td class="text-center">@item.TotalReceived</td>
                            <td class="text-center"><input type="text" class="form-control Receivedqty" /></td>
                            <td class="text-center"></td>

                        </tr>
                    }
                </table>
            </div>

        </div>
        <div id="horizontal-form" class="p-5">
            <div class="preview">
                <div class="form-inline">
                    <label for="horizontal-form-1" class="form-label sm:w-20"><strong>Upload Doc </strong></label>
                    <input type="file" id="UploadDoc" name="UploadDoc" class="form-control" />
                </div>
            </div>
        </div>

        <div class="sm:pl-5 mt-1 mb-5">
            <input type="submit" value="Submit" id="add" class="btn btn-primary" />
            <!-- END: Data List -->
        </div>
        <input type="hidden" name="jobworkdesc">

    }
</form>
<!-- BEGIN: Delete Confirmation Modal -->
@section Scripts {
    <script>
        $("#add").click(function() {
            var indentdesc = new Array();
            $('#orders tr').each(function(i, row) {
                var ItemId = $(this).closest('tr').find("td").eq(0).html();
                var Challanqty = $(this).closest('tr').find("td:eq(5) input").val();
                var RcvdQty = $(this).closest('tr').find("td:eq(4) input").val();
                var po = {};
                po.ItemId = ItemId;
                po.Challanqty = Challanqty;
                po.RcvdQty = RcvdQty;
                indentdesc.push(po);
            });
            document.getElementsByName("jobworkdesc")[0].value = JSON.stringify(indentdesc);
        });


        $(document).ready(function() {

            $(document).on('input', '#orders .Receivedqty', function() {
                var currentRow = $(this).closest("tr");
                var ActualQty = currentRow.find("td:eq(2) input").val();
                var Rcvdqty = currentRow.find("td:eq(4) input").val();               
                var Balanceqty = parseFloat(ActualQty - Rcvdqty);                 
                currentRow.find("td:eq(5)").html(Balanceqty);
                
            });
        });
    </script>

}

Areas/HeadOffice/Pages/PO/Index.cshtml
@page "{handler?}"
@model Nkgjjm.Areas.Panel.Pages.PO.IndexModel

@{
    ViewData["Title"] = "Index";
    int i = 1;
}
<div class="top-bar">
    <nav aria-label="breadcrumb" class="-intro-x mr-auto hidden sm:flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Application</a></li>
            <li class="breadcrumb-item active" aria-current="page">Purchase Order Pending List</li>
        </ol>
    </nav>
    <!-- END: Account Menu -->
</div>
<h2 class="intro-y text-lg font-medium mt-0" style="background-color:#02B9B5; text-align:center; font-weight:bolder; color:white;">
    Purchase Order Pending List
</h2>
<div class="grid grid-cols-12 gap-6 mt-1">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a class="btn btn-primary shadow-md mr-2" asp-page="Create">Add New Purchase Order</a>

        <div class="hidden md:block mx-auto text-slate-500">Total @Model.TotalPo Po(s)</div>
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <div class="w-56 relative text-slate-500">
                <form method="get" asp-page-handler="Search">
                    <input type="text" class="form-control w-56 box pr-10" name="PoNo" placeholder="Search...">
                    <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-lucide="search"></i>
                </form>
            </div>
        </div>
    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report">
            <thead>
                <tr>

                    <th class="text-center whitespace-nowrap">
                        S.No.
                    </th>
                    <th class="text-center whitespace-nowrap">
                        PO. No.
                    </th>
                    <th class="text-center whitespace-nowrap">
                        @Html.DisplayNameFor(model => model.PoMaster[0].Date)
                    </th>
                    <th class="text-center whitespace-nowrap">
                        @Html.DisplayNameFor(model => model.PoMaster[0].Buyer)
                    </th>
                    <th class="text-center whitespace-nowrap">
                        @Html.DisplayNameFor(model => model.PoMaster[0].CompanyName)
                    </th>

                  @*  <th class="text-center whitespace-nowrap">Action</th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PoMaster)
                {
                    <tr>
                        <td class="text-center">@i</td>
                        <td style="color:blue;" class="text-center">
                            <a asp-page="/Po/PoDetail" asp-route-PoNo="@item.Pono">
                            @item.Pono
                            </a>
                        </td>
                        <td class="text-center">
                            @item.Date.ToShortDateString()
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.Buyer)
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.CompanyName)
                        </td>

                        @*<td class="table-report__action w-56">
                            <div class="flex justify-center items-center">
                                <a class="flex items-center mr-3" asp-page="Edit" asp-route-PoNo="@item.Pono"> <i data-lucide="check-square" class="w-4 h-4 mr-1"></i> Edit </a>




                            </div>
                        </td>*@
                    </tr>
                    i++;
                }
            </tbody>
        </table>
    </div>
    <!-- END: Data List -->
</div>
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal" class="modal" tabindex="-1" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-lucide="x-circle" class="w-16 h-16 text-danger mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-slate-500 mt-2">

                        Do you really want to delete these records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <input type="hidden" id="dataid" />
                    <button type="button" data-tw-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <button type="button" id="mdlDelete" class="btn btn-danger w-24">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>